# Site settings
title: mersinvald's blog
description: >
  Rust, Web, Async, Blockchain and The Dark Size of The Force
baseurl: "/" # should be / if you build a global github page (eg o0ignition0o.github.io)
url: "https://blog.mkl.dev" # The blog url you want to choose (you can use a github.io one, or pick your own hosted url :))
logo: "https://s.gravatar.com/avatar/fbc2137221663891b1e6affde8566823?s=64" # This one is used as blog logo
twitter_username: mersinvald # Your twitter handle
github_username: mersinvald # Your github handle

# Build settings
highlighter: rouge

root: "https://blog.mkl.dev" # Not really sure this is useful, need to cross check with blog writers :)

theme: jekyll-theme-midnight